apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GitHub
  description: GitHub Integration
  annotations:
    github.com/project-slug: harishc-biz/thoughtworks_mediawiki
    github.com/repo: thoughtworks_mediawiki
    github.com/branch: main
    github.com/issues-url: https://github.com/harishc-biz/thoughtworks_mediawiki/issues 
    github.com/pull-requests-url: https://github.com/harishc-biz/thoughtworks_mediawiki/pulls
    github.com/wiki-url: https://github.com/harishc-biz/thoughtworks_mediawiki/wiki
  links:
    - url: https://github.com/harishc-biz/thoughtworks_mediawiki
      title: GitHub Repository
    - url: https://github.com/harishc-biz/thoughtworks_mediawiki/issues
      title: Issue Tracker
    - url: https://github.com/harishc-biz/thoughtworks_mediawiki/wiki
      title: Wiki
spec:
  type: website
  owner: Harish
  lifecycle: experimental
  dependsOn:
    - github.com:api

  tags:
    - github
    - integration
    - backstage
    - experimental
